Enable plotting from tiled and launching a latent space extraction through an autoencoder
runboj/mlex_latent_explorer pull request #8
Opened 2024-03-28 04:55 UTC by taxe10

This PR addresses some minor bugs in the current version of latent space explorer:
- Enables plotting tiled data when selecting data points from the latent space plot
- It corrects the orientation of the data, which were upside down
- Enables running the application outside of docker through the definition of env variables
- Replaced env file for env.example file and updated gitignore file
- Rearranged plots to be side-by-side
- Added an optional autoencoder inference step to be run prior dimension reduction
- Added job dropdown with previously ran jobs
- Added conda flows as an alternative to podman jobs

2024-03-28 20:02 UTC, runboj commented
Hi Tanny, what is "CONTENT_API_URL" used for? @taxe10

2024-03-28 21:35 UTC, taxe10 commented
> Hi Tanny, what is "CONTENT_API_URL" used for? @taxe10

The CONTENT_API_URL is used to set up the url to the content registry api, which could be "localhost:8000" outside docker or "content_registry:8000" within docker, or any other custom setups

2024-03-29 00:59 UTC, runboj requested changes

2024-03-29 00:59 UTC, runboj commented on .env.example
> +OUTPUT_DIR=/path/to/output  # optional - if not provided, will default to data
Do we need output_dir?

2024-03-29 00:59 UTC, runboj commented on .env.example
> +CONTENT_API_URL="http://localhost:8000/api/v0/models"
This is the content registry api

2024-03-29 00:59 UTC, runboj commented on .env.example
> +DATA_DIR=/path/to/data
For this DATA_DIR, can you give me an example way to format it? Would "/app/work/data" work when running in Docker on my mac?

2024-03-29 17:26 UTC, taxe10 commented on .env.example
> +OUTPUT_DIR=/path/to/output  # optional - if not provided, will default to data
No, but I decided to restructure the variables to `READ_DIR` and `WRITE_DIR`, where each define a directory path to read files from and the other defines the directory path where to store results

2024-03-29 17:29 UTC, taxe10 commented on .env.example
> +DATA_DIR=/path/to/data
In my machine, the READ_DIR is set to `/Users/tanny/Documents/Data` as I have some few datasets stored there, and the WRITE_DIR is set to `/Users/tanny/Documents/Results`

2024-03-29 20:33 UTC, merged